"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['RecipeApp.py']
DATA_FILES = ['recipe.db']
OPTIONS = {'argv_emulation': True,
           'includes': ['six', 'appdirs', 'packaging', 'packaging.version', 'packaging.specifiers',
                        'packaging.requirements'],
           'iconfile': 'icon.icns'            
          }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
)
